
# {{{ health checkers

GET http://localhost:8080/health
GET # workaround

# }}}

# {{{
POST http://localhost:8080/auth/signup
Accept: application/json
Content-type: application/json

{
  "username": "user",
  "password": "user",
  "project": "projects:g1"
}

POST http://localhost:8080/auth/login
Accept: application/json
Content-type: application/json

{
  "username": "user",
  "password": "user"
}

GET http://localhost:8080/auth/refresh
Accept: application/json
Authorization: Bearer 
Content-type: application/json
# }}}

# {{{ will be removed
POST http://localhost:8080/auth/refresh
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "ns": "global",
  "db": "main",
  "token": ""
}

## kenny
POST http://localhost:8080/auth/join
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "ns": "demo",
  "db": "demo",
  "pass": "01HWX5KJ8KGE7HKPRST4R5PYYW"
}

## does not work
POST http://localhost:8080/auth/join
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "ns": "demo",
  "db": "demo",
  "pass": "guest"
}

POST http://localhost:8080/auth/refresh
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "ns": "demo",
  "db": "demo",
  "token": ""
}

POST http://localhost:8000/signin
Accept: application/json
Content-Type: application/json

{
  "ns": "demo",
  "db": "demo",
  "sc": "user",
  "pass": "01HJTEBG4Y1EAXPATENCDCT7WW"
}
# }}}
