
# {{{ health checkers

GET http://localhost:8080/health
GET # workaround

# }}}

### modules
# {{{ AUTH

POST http://localhost:8080/auth/login
Accept: application/json
Content-type: application/json

{
  "username": "guest"
}

POST http://localhost:8080/auth/refresh
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "ns": "global",
  "db": "main",
  "token": ""
}

POST http://localhost:8080/auth/join
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "ns": "interventions",
  "db": "demo",
  "pass": "guest"
}

POST http://localhost:8080/auth/refresh
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "ns": "interventions",
  "db": "demo",
  "token": ""
}

### will be removed
POST http://localhost:8000/signin
Accept: application/json
Content-Type: application/json

{
  "ns": "interventions",
  "db": "demo",
  "sc": "user",
  "pass": "01HJTEBG4Y1EAXPATENCDCT7WW"
}

# }}}

GET http://localhost:8000/key/papers
Accept: application/json
Authorization: Bearer 

# {{{ 
GET http://localhost:8080/
Accept: application/json

GET http://localhost:8080/foo
Accept: application/json

# }}}
